language: node_js
node_js:
  - "8"
before_script:
  - npm run test
script:
  - npm run build
before_deploy:
  - cd ./dist
deploy:
  provider: heroku
  api_key: $HEROKU_KEY
  app: polyglot-keyboard
  skip_cleanup: true